ALTER TABLE userz DROP COLUMN IF EXISTS agepsw;

ALTER TABLE userz DROP COLUMN IF EXISTS compname;

ALTER TABLE userz DROP COLUMN IF EXISTS licence;

ALTER TABLE userz DROP COLUMN IF EXISTS support;

ALTER TABLE userz DROP COLUMN IF EXISTS license;

ALTER TABLE userz DROP COLUMN IF EXISTS prefix;